# Generated by Django 4.0.5 on 2022-07-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagemo',
        ),
    ]
