# Generated by Django 4.0.5 on 2022-07-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_image_imagemo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagemo',
            new_name='Imagemodel',
        ),
    ]
